### ISSUE TITLE
NPE at net.datafaker.service.FakeValuesService.fetchObject():268

### ISSUE THREAD

**Issue by axelfontaine** [datafaker-net/datafaker#1412] opened 2024-10-29 10:17 UTC
**Describe the bug**
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "net.datafaker.internal.helper.CopyOnWriteMap.getOrDefault(Object, Object)" is null
      at net.datafaker.service.FakeValuesService.fetchObject(FakeValuesService.java:268)
      at net.datafaker.service.FakeValuesService.safeFetch(FakeValuesService.java:207)
      at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:507)
      at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:489)
      at net.datafaker.providers.base.AbstractProvider.resolve(AbstractProvider.java:20)
      at net.datafaker.providers.base.Animal.name(Animal.java:15)
```

Similar, but not identical to #1403 which was resolved in 2.4.1.

**To Reproduce**
Failure is intermittent and probably due to a concurrency issue when running multiple tests in parallel which all try to initialize datafaker at the same time

**Expected behavior**
No NPE

**Versions:**
 - OS: Win 11 x64
 - JDK: 22
 - Faker Version: 2.4.1

**Comment by bodiam** [comment] 2024-10-29 10:49
Hi @axelfontaine, 

Thanks for reporting. We are aware of this, it's maybe related to the CopyOnWrite map, or some odd initialisation or cleanup. I know @asolntsev gave it a good attempt, but so far we've been unable to get to the root cause of this. If you want, you might want to give it a try by replacing the COW map by a HashMap, but I believe @asolntsev mentioned the issue wasn't there.

**Comment by asolntsev** [comment] 2024-10-31 20:42
Hope it's fixed by https://github.com/datafaker-net/datafaker/pull/1419

**Closed** 2024-11-01 10:55 UTC
Labels: bug

**Comment by bodiam** [comment] 2024-11-04 13:06
@axelfontaine could you please verify using the snapshot version if it's fixed? If yes, we'll release another version.

**Comment by axelfontaine** [comment] 2024-11-04 13:18
@bodiam Do you have a snapshot repo I can reference in my build so I can pull it?

**Comment by kingthorin** [comment] 2024-11-04 13:26
https://www.datafaker.net/documentation/getting-started/#snapshot-versions

```
repositories {
    mavenCentral()
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots")
}

dependencies {
    implementation("net.datafaker:datafaker:2.4-2-SNAPSHOT")
}
```

**Comment by axelfontaine** [comment] 2024-11-04 14:37
@kingthorin Did you try it?

This fails for me with

```
Could not find net.datafaker:datafaker:2.4-2-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/net/datafaker/datafaker/2.4-2-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/net/datafaker/datafaker/2.4-2-SNAPSHOT/datafaker-2.4-2-SNAPSHOT.pom
  - https://s01.oss.sonatype.org/content/repositories/snapshots/net/datafaker/datafaker/2.4-2-SNAPSHOT/maven-metadata.xml
  - https://s01.oss.sonatype.org/content/repositories/snapshots/net/datafaker/datafaker/2.4-2-SNAPSHOT/datafaker-2.4-2-SNAPSHOT.pom
```

**Comment by kingthorin** [comment] 2024-11-04 14:45
I hadn't, I was trusting the docs 😉

Lemme see what else I can find.

**Comment by asolntsev** [comment] 2024-11-04 15:18
@kingthorin The documentation is correct, you just mispelled the version number.

@axelfontaine Please try this dependency:
```
dependencies {
    implementation("net.datafaker:datafaker:2.4.1-SNAPSHOT")
}
```

**Comment by kingthorin** [comment] 2024-11-04 15:18
It looks like we missed a change for the recent release: https://s01.oss.sonatype.org/content/repositories/snapshots/net/datafaker/datafaker/

If you try the latest 2.4.1 snapshot which seems to be dated Sunday it should have the fix though it is attributed to the wrong version . 

https://s01.oss.sonatype.org/content/repositories/snapshots/net/datafaker/datafaker/

**Comment by axelfontaine** [comment] 2024-11-04 15:40
Alright, I integrated 2.4.1-SNAPSHOT into our build. The NPE was only intermittent, so no reliable way to trigger it, but so far so good.

**Comment by kingthorin** [comment] 2024-11-09 15:20
@bodiam could you enable this option in Settings > Actions?
![image](https://github.com/user-attachments/assets/c2b7c780-1db0-4bf8-b6e3-72ad6e820625)

I'll then add a workflow called from the release workflow which will increment the version in pom.xml and submit a PR automatically.

**Comment by bodiam** [comment] 2024-11-10 03:23
@kingthorin done!
