### ISSUE TITLE
`ConcurrentModificationException` when using parallel test execution

### ISSUE THREAD

**Issue by unki2aut** [datafaker-net/datafaker#256] opened 2022-07-28 09:46 UTC
**Describe the bug**
With the upgrade from version `1.4.0` to `1.5.0` one of my tests started to fail with a `ConcurrentModificationException`.

**To Reproduce**
This could also be reproduced within an empty gradle project with only this test:

```java
import net.datafaker.Faker;
import org.junit.jupiter.api.Test;

public class FakerConcurrencyModificationExceptionTest {

    private final Faker faker = new Faker();

    @Test
    public void test1() {
        faker.random().nextLong();
    }

    @Test
    public void test2() {
        faker.random().nextLong();
    }
}
```

**junit-platform.properties**
```properties
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
```

**Expected behavior**
Tests don't fail with this exception.

**Versions:**
 - OS: OSX 12.3.1
 - JDK 17.0.4
 - Faker Version 1.5.0

**Comment by snuyanzin** [comment] 2022-07-31 14:21
It seems it should be fixed with https://github.com/datafaker-net/datafaker/pull/267
@unki2aut  could you please check if the issue is fixed or not?

**Comment by unki2aut** [comment] 2022-08-01 08:47
@snuyanzin thank you for the quick turnaround! Had a look at the code and seems good to me 👍

**Closed** 2022-08-01 13:47 UTC
