### ISSUE TITLE
Does version 2.0.1 work with GraalVM 22.3.2 Java 17 CE?

### ISSUE THREAD

**Issue by dxxvi** [datafaker-net/datafaker#877] opened 2023-06-23 23:01 UTC
**Describe the bug**
Use it in a very simple Spring Boot 3.1.1 app, build that app with `gradlew bootBuildImage` and the result is a docker image. Run that docker image `docker run --rm -p 8080:8080 my-image` then
```
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: name.first_name resulted in null expression
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:444)
        at net.datafaker.service.FakeValuesService.resolve(FakeValuesService.java:423)
        at net.datafaker.providers.base.AbstractProvider.resolve(AbstractProvider.java:18)
        at net.datafaker.providers.base.Name.firstName(Name.java:61)
```

**To Reproduce**
[Create a spring boot 3.1.1 app](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.developing-your-first-application) at start.spring.io (java 17, gradle, add the GraalVM Native Support dependency) 

`build.gradle` looks like this:
```
plugins {
  id 'java'
  id 'org.springframework.boot' version '3.1.1'
  id 'io.spring.dependency-management' version '1.1.0'
  id 'org.graalvm.buildtools.native' version '0.9.23'
}
...
dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-actuator'
  implementation 'net.datafaker:datafaker:2.0.1'
  compileOnly 'org.projectlombok:lombok'
  annotationProcessor 'org.projectlombok:lombok'
}
```
The main and single class is
```
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;
import net.datafaker.Faker;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

public @Slf4j @RestController @SpringBootApplication(proxyBeanMethods = false) class Application {
  public static final String APP_NAME = new Faker().name().firstName();

  public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
  }

  public @GetMapping("/api/env") Map<String, Object> get() {
    var result = new LinkedHashMap<String, Object>();
    result.put("time", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
    result.put("name", APP_NAME);
    result.put("properties", System.getProperties());
    result.put("env", System.getenv());
    log.debug("APP_NAME {} in get method", APP_NAME);
    return result;
  }
}
```
Build the app with `gradlew bootBuildImage`

**Versions:**
 - OS: WSL2 in Windows 10
 - JDK: 17
 - Faker Version: 2.0.1

Edit: Ah, `BaseFaker` uses reflections. However, I still don't know how to fix this issue.

**Comment by kingthorin** [comment] 2023-06-23 23:38
Instantiate the faker before you try to use it?

**Comment by bodiam** [comment] 2023-06-24 04:34
@dxxvi good question. Due to our use of resource loading, reflection, etc, it might not be very straightforward to make it run on GraalVM, and GraalVM isn't part of our build  matrix at the moment. So let's say that at the moment, GraalVM isn't supported.

However, it would be great if we did support it. If you have some suggestions, or maybe (part of) a PR which we could use a a starting point, that would be great.

**Comment by bodiam** [comment] 2023-06-25 03:45
I've tried to reproduce the issue, but I can't compile the application:

```
    [creator]     ================================================================================
    [creator]     GraalVM Native Image: Generating '/layers/paketo-buildpacks_native-image/native-image/demo.DemoApplication' (static executable)...
    [creator]     ================================================================================
    [creator]     [1/7] Initializing...                                           (42.5s @ 0.31GB)
    [creator]      Version info: 'GraalVM 22.3.2 Java 17 CE'
    [creator]      Java version info: '17.0.7+7-LTS'
    [creator]      C compiler: gcc (linux, x86_64, 7.5.0)
    [creator]      Garbage collector: Serial GC
    [creator]      1 user-specific feature(s)
    [creator]      - org.springframework.aot.nativex.feature.PreComputeFieldFeature
    [creator]     Error: Image build request failed with exit status 137
    [creator]     unable to invoke layer creator
    [creator]     unable to contribute native-image layer
    [creator]     error running build
    [creator]     exit status 137
    [creator]     ERROR: failed to build: exit status 1
```

Suggestions?

**Comment by snuyanzin** [comment] 2023-06-25 08:17
137 exit status is usually related to out of memory, probably you need to increase it.

I was able to reproduce the reported issue  however it seems not an issue of datafaker, 
it is more an issue of how image was created because while creation of image we should keep in mind all resource files for datafaker.

**Comment by kingthorin** [comment] 2024-01-05 02:29
No input from the reporter since last June. Closing due to lack of input/evidence. If you have further details to add please comment and we could consider re-opening.

**Closed by kingthorin** 2024-01-05 02:29 UTC

**Comment by bodiam** [comment] 2024-10-13 01:11
I know it's a bit late, but I added some support for GraalVM here: https://github.com/datafaker-net/datafaker/pull/1376
